curl -X POST -v 'localhost:8080/join?username=grecia'
curl -X POST -v 'localhost:8080/join?username=mati'
curl -X POST -v 'localhost:8080/join?username=capi'
curl -X POST -v 'localhost:8080/join?username=dai'
curl -X POST -v 'localhost:8080/join?username=agus'
curl -X POST -v 'localhost:8080/join?username=klaus'
curl -X POST -v 'localhost:8080/join?username=ari'
curl -X POST -v 'localhost:8080/join?username=jonas'

curl -X POST -v 'localhost:8081/join?username=grecia'
curl -X POST -v 'localhost:8081/join?username=mati'
curl -X POST -v 'localhost:8081/join?username=capi'
curl -X POST -v 'localhost:8081/join?username=dai'
curl -X POST -v 'localhost:8081/join?username=agus'
curl -X POST -v 'localhost:8081/join?username=klaus'
curl -X POST -v 'localhost:8081/join?username=ari'
curl -X POST -v 'localhost:8081/join?username=jonas'
