kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster-chat
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 32500
    hostPort: 8558
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 32000
    hostPort: 8080
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 32600
    hostPort: 9042
    listenAddress: "127.0.0.1"
    protocol: TCP
