apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterchat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clusterchat
  template:
    metadata:
      labels:
        app: clusterchat
    spec:
      containers:
        - name: clusterchat
          image: <your-docker-username>/clusterchat:latest
          ports:
            - containerPort: 8080

              ---
apiVersion: v1
kind: Service
metadata:
  name: clusterchat
spec:
  type: ClusterIP
  selector:
    app: clusterchat
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
